### PR TITLE
App event exited

### PR DESCRIPTION
**Pull request by Shallowmallow**
Adding app event exited :)

### CODE REVIEW

**Comment by ianharrigan** [comment]
Alright, i understand, you renamed app_closed to app_exited? And implemented it for openfl?

**Comment by Shallowmallow** [comment]
Yeah, I planned to do an Closed event at first, but as it was onExit in
openfl, It was more coherent to be be an exited event.
(Plus I'm not sure of the difference between the two, for me instinctively,
"close" is a user event, and "exit" is an app event, like if the app
crashed  , it should dispatch an exit and not a close event)


Le mer. 14 juin 2023 à 11:13, Ian Harrigan ***@***.***> a
écrit :

**Comment by ianharrigan** [comment]
I think thanks fair... this change will break haxeui-hxwidgets though... (which uses the close event)... do you want to make the change? Or shall I?

**Comment by Shallowmallow** [comment]
Seems  hxwidgets uses both
APP_CLOSED when there is an EventType.CLOSE_WINDOW on the main windowand
APP_EXITED once the app has run.

Why would it need a change ?

Le mer. 14 juin 2023 à 12:04, Ian Harrigan ***@***.***> a
écrit :

**Comment by ianharrigan** [comment]
oh, my bad, i read the code completely wrong... i thought _you_ renamed app_closed to app_exited... i didnt realise both already existed...

**Pull request merged**
